baseURL = "http://wereonlyalittlelost.com/"
languageCode = "en-us"
title = "We're Only a Little Lost"
summary = "Testing"
theme = "lost_theme"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
features = ["trips", "about"]
Paginate = 10

[params]
  favicon = "/images/favicon.png"
  tagline = "Pam and Co Travel Around Texas, the Country and Beyond!"
  description = "It's an adventure"
  instagram = "https://www.instagram.com/battlemaid01"
  youtube = "https://www.youtube.com/channel/UCx4SjesqsItUdbYmy_aJXzA"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/cover_image.jpg"
  recent_posts_number = 1
  recent_copy = "Latest Post"
  home = "Home"

[author]
  name = "Pam"