seURL = "http://wereonlyalittlelost.com/"
languageCode = "en-us"
title = "We're Only a Little Lost"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10

[params]
  favicon = "/images/favicon.jpg"
  description = "It's an adventure"
  instagram = "instagram.com/battlemaid01"
  youtube = "https://www.youtube.com/channel/UCx4SjesqsItUdbYmy_aJXzA"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/cover_image.jpg"
  recent_posts_number = 1